<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please transfer the total amount to t_a6d3bd</name>
   <tag></tag>
   <elementGuidId>bd9d2fdf-aebe-4fb8-93e8-15abf34cd6d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='button-confirm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button-confirm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69e0c8ae-f74c-4021-ae90-8011938d95b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9b7b80e5-bece-497e-9ee8-f182b12a5dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Confirm Order</value>
      <webElementGuid>75787ca5-67de-4ab9-8633-681b4ef29c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-confirm</value>
      <webElementGuid>d6ebc639-ed58-424a-baf1-120bcfc66826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loading-text</name>
      <type>Main</type>
      <value>Loading...</value>
      <webElementGuid>2b1fdce2-870a-4f7a-8cd3-0d1c4e09a18c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>f7ceb0fa-680f-4e65-b89b-24707cdb60e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-confirm&quot;)</value>
      <webElementGuid>c661fc56-a368-4e98-b3ee-d09864b7243f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='button-confirm']</value>
      <webElementGuid>b5889202-a4fc-44e4-bbcf-a0fe7c569dc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapse-checkout-confirm']/div/div[3]/div/input</value>
      <webElementGuid>4d10c759-00d7-471c-921b-ad2413b50a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/input</value>
      <webElementGuid>9e4b3f75-09a2-47b3-8076-9891a4392055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'button-confirm']</value>
      <webElementGuid>517d5a3d-2035-4d45-9a4f-a64f4e701eca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
