<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--- Please Select --- ArtigasCanelon_9a742f</name>
   <tag></tag>
   <elementGuidId>2747897d-1a10-4394-874f-2006a06b20fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='input-payment-zone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-payment-zone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7c64570c-5c7a-4a95-982b-8605284b662b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zone_id</value>
      <webElementGuid>5dda72c9-ebc8-499b-9ae3-396e7d659b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-payment-zone</value>
      <webElementGuid>24e44f05-43af-4558-925c-54363bd7c878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e48fc56b-91f4-401b-9e51-63412c0e1569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> --- Please Select --- ArtigasCanelonesCerro LargoColoniaDuraznoFloresFloridaLavallejaMaldonadoMontevideoPaysanduRio NegroRiveraRochaSaltoSan JoseSorianoTacuaremboTreinta y Tres</value>
      <webElementGuid>11e224e0-de5d-47a7-8b3f-21b74fcbd17d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-payment-zone&quot;)</value>
      <webElementGuid>8f94f88e-f28e-4af9-960f-ed934263b177</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='input-payment-zone']</value>
      <webElementGuid>01f29261-2ef1-4296-993e-3bb6339a5cba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-new']/div[9]/div/select</value>
      <webElementGuid>4b20d757-5edc-47e0-b46a-1709743878f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Region / State'])[1]/following::select[1]</value>
      <webElementGuid>b014816e-7a26-49b0-9c18-f17cd5b9f300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/following::select[2]</value>
      <webElementGuid>3ae66b55-3efd-4222-be25-1bc2b650c10c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Step 3: Payment Method'])[1]/preceding::select[1]</value>
      <webElementGuid>140836a2-f874-46af-9e4b-002ba4494add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Step 4: Confirm Order'])[1]/preceding::select[1]</value>
      <webElementGuid>753b414c-c646-4f42-a619-c2b3b0a73780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/select</value>
      <webElementGuid>c95e50ae-9491-4257-922d-6f5f3366eb8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'zone_id' and @id = 'input-payment-zone' and (text() = ' --- Please Select --- ArtigasCanelonesCerro LargoColoniaDuraznoFloresFloridaLavallejaMaldonadoMontevideoPaysanduRio NegroRiveraRochaSaltoSan JoseSorianoTacuaremboTreinta y Tres' or . = ' --- Please Select --- ArtigasCanelonesCerro LargoColoniaDuraznoFloresFloridaLavallejaMaldonadoMontevideoPaysanduRio NegroRiveraRochaSaltoSan JoseSorianoTacuaremboTreinta y Tres')]</value>
      <webElementGuid>c632435d-a6f0-4a8c-baf0-e461df909a81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
